version: "3"
services:
  database:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=xpire
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/ # persist data even if the container shuts down
  backend:
    build: .
    env_file: ".env"
    links:
      - "database:database"
    depends_on:
      - database
    ports:
      - "8000:8000"
