version: "3"
services:
  database:
    image: "postgres:latest"
    environment:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/ # persist data even if the container shuts down
